datasource:
  username : root
  password: root
  url: jdbc:mysql://localhost:3306/test
  driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8090
  servlet:
    context-path: /zhg

spring:
  redis:
    database: 0
    host:  localhost
    port: 6379
    password: root



  devtools:
    restart:
     enabled: true

  mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8





















